project:
  type: website

website:
  title: "AAI1001 Data Engineering and Visualization Assessment 3"
    
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    embed-resources: true



